function [Storm, storm2rm] = chs_peaks_formater(swl_peaks_table, hm0_peaks_table, STWAVE_headers_location, storm_duration, Tp_special)
%{
    %% DESCRIPTION
    This function parses converted CHS data structure to generate a
    number_of_storms x 4 data matrix containing provided CHS regional study
    storm peak values. 
    
    %% INPUTS
    ADCIRC: Converted CHS peaks storm data in table format. This dataset
    can be generated by converting CHS data files using StormSim's h5
    converter (H5_Converter.m). 
    
    %% OUTPUTS
    config: MATLAB data strcutre containing input file data parsed out as
    individual strucutre fields.
    
    %% DEV SIGNATURE
    Developed by: Fabian A. Garcia Moreno ERDC-CHL
%}

%% INITIALIZE VARIABLES
% Initialize Storm Matrix
Storm = zeros(height(swl_peaks_table),6);

%% STORM SURGE (ADCIRC) 
% Get Storm Data Table
swl_peaks_table = sortrows(swl_peaks_table,'Storm ID','ascend');
% Extract Storm ID From ADCIRC Table
stm_id = num2cell(str2double(swl_peaks_table.("Storm ID")));
% Extract Water Level From ADyCIRC Table
Storm(:,1) = swl_peaks_table.("Water Elevation");
% Assign NaN's If Needed
Storm(Storm(:,1)<-90,1) = NaN(1,1);

%% WAVES (STWAVE, SWAN, WAM)
% Sort Data Table
hm0_peaks_table = sortrows(hm0_peaks_table,'Storm ID','ascend');
%%%%%% Hm0 %%%%%%%
% Extract Hm0 Peak Values From Data Table
Storm(:,2) = hm0_peaks_table.(STWAVE_headers_location.Hm0);
%%%%%% Tp %%%%%%
% Extract Peak Period From STWAVE Tabley
Storm(:,3) = hm0_peaks_table.(STWAVE_headers_location.Tp);
% Convert From Tm to Tp (Special Case)
if Tp_special == 1
    % Convert Tm to Tp (Lake Ontario Case)
    Storm(:,3) = Storm(:,3)*1.2;  % Remove This For Release, Need to inform user
end
%%%%%% Wave Direction %%%%%%
% Extract Wave Direction From STWAVE Table
Storm(:,4) = hm0_peaks_table.(STWAVE_headers_location.wDir);
% Assign NaN's If Needed
Storm(sum(Storm(:,2:4)<-90,2)>=1,2:4) = NaN(1,1);
Storm(sum(Storm(:,2:4)==0,2)>=1,2:4) = NaN(1,1);
% Check For NaT
nan_rows = isnat(swl_peaks_table.("yyyymmddHHMM"));
% Assign NaN
Storm(nan_rows,5) = NaN;
Storm(~nan_rows,5) = datenum(swl_peaks_table.("yyyymmddHHMM")(~nan_rows));
% Storm Duration
Storm(:, 6) = storm_duration;
% Find NaN's In "Default" Dataset
storm2rm = cell2mat(stm_id(unique([find(isnan(Storm(:,1)));find(isnan(Storm(:,2)));...
    find(isnan(Storm(:,3)));find(isnan(Storm(:,4)))])));
% Append Data
Storm = [stm_id, num2cell(Storm, 2)];
end
