function [storm_data, ts_storm2rm] = chs_timeseries_formater(swl_timeseries, hm0_timeseries, storms2rm,...
    STWAVE_headers_location, Tp_special)
%{
    %% DESCRIPTION
    This function parses converted CHS data structure to generate a
    number_of_storms x  9 data matrix containing provided CHS regional study
    storm timeseries values. 
    
    %% INPUTS
    swl_timeseries: Converted CHS ADCIRC timeseries storm data in table format. This dataset
                    can be generated by converting CHS data files using StormSim's h5
                    converter (H5_Converter.m). 
    hm0_timeseries: Converted CHS STWAVE timeseries storm data in table format. This dataset
                    can be generated by converting CHS data files using StormSim's h5
                    converter (H5_Converter.m). 
    storms2rm:      Storm ID's of bad storms.
    has_WaterElevation: Boolean indicating if wave model output includes
                        water elevation outputs. Output from 
                        chs_wave_model_header_locator.m

    STWAVE_headers_location: Column index of Hm0, Tp and wave direction in
                             CHS STWAVE outputs. Output from
                             chs_wave_model_header_locator.m
    %% OUTPUTS
    storm_data: MATLAB data structure containing formated chs timeseries
    data.
    
    %% DEV SIGNATURE
    Developed by: Fabian A. Garcia Moreno ERDC-CHL
%}

%% DEFINE INPUTS
%
ts_storm2rm = storms2rm;
% Display Completion Progress Initial Print
fprintf(1,'   Completion Progress: %3d%%\n',0);
% Ensure Data Is Sorted Per Storm ID
swl_timeseries = sortrows(swl_timeseries,'Storm ID','ascend');
hm0_timeseries = sortrows(hm0_timeseries,'Storm ID','ascend');
stmID = cellfun(@str2double,swl_timeseries.('Storm ID'), 'un', false);
% Initialize Storage Matrix
storm_data = [stmID ,cell(length(stmID(:,1)),1)];

%% ADCIRC-STWAVE TIMESERIES MATCHING PROCESS
% Loop Through All Storms
for stm = 1:length(stmID)
    % Print Status
    fprintf(1,'\b\b\b\b%3.0f%%',(100*(stm/length(stmID))));
    % Skip Bad Storm
    if ismember(stmID{stm},storms2rm) || length(swl_timeseries.("Water Elevation"){stm,1}) == 1
        % Assign NaN
        storm_data(stm, 2) = {nan(1,1)};
        % Store Bad Storm ID
        ts_storm2rm = [ts_storm2rm;stmID{stm}];
        % Move To Next Storm
        continue;
    end

    %% EXTRACT STORM DATA
    % Get Storm Row Index
    pull_indx = cell2mat(stmID) == stmID{stm};
    % ADCIRC
    WL = swl_timeseries.("Water Elevation"){pull_indx,1};
    WL_datestr = num2str(swl_timeseries.("yyyymmddHHMM"){pull_indx,1});

    % STWAVE
    waves = [hm0_timeseries.(STWAVE_headers_location.Hm0){pull_indx,1},...
        hm0_timeseries.(STWAVE_headers_location.Tp){pull_indx,1},...
        hm0_timeseries.(STWAVE_headers_location.wDir){pull_indx,1}];

    % Determine Date Format
    dformat = 'yyyyMMddHHmmss';
    ad_len = length(num2str(swl_timeseries.("yyyymmddHHMM"){pull_indx,1}(1, :)));
    wv_len = length(num2str(hm0_timeseries.("yyyymmddHHMM"){pull_indx,1}(1, :)));


    wv_dtime = datetime(num2str(hm0_timeseries.("yyyymmddHHMM"){pull_indx,1}), "InputFormat", dformat(1:wv_len));
    ad_dtime = datetime(num2str(swl_timeseries.("yyyymmddHHMM"){pull_indx,1}), "InputFormat", dformat(1:ad_len));
    dt_wv = unique(diff(wv_dtime));dt_wv = dt_wv(1);
    dt_ad = unique(diff(ad_dtime));dt_ad = dt_ad(1);

    % Lake Ontrario Special Case
    if Tp_special == 1
        waves(:,3) = waves(:,3).*1.2;
    end

    %% EXTRACT ADCRIC DATA THAT RESIDES INSIDE STWAVE TEMPORAL RANGE
    % Extract ADCIRC Data Points Within Time Window
    WL = WL(ad_dtime>=min(wv_dtime) & ad_dtime<=max(wv_dtime), :);
    ad_dtime = ad_dtime(ad_dtime>=min(wv_dtime) & ad_dtime<=max(wv_dtime), :);

    %% ADJUST MODEL OUTPUTS (IF NEEDED)
    % Adjust Storm Time Matching (If Needed)
    if dt_ad > dt_wv
        % Determine Stride For Data Pull To Match ADCIRC Model
        tstp_stride = dt_ad/dt_wv;
        % Limit Indexing To integer Values
        if mod(tstp_stride,1) == 0
            waves = waves(1:tstp_stride:end, :);
            wv_dtime = wv_dtime(1:tstp_stride:end,:);
            dt_final = datenum(dt_ad);
        end
    elseif dt_ad < dt_wv
        % Determine Stride For Data Pull To Match Wave Model
        tstp_stride = dt_wv/dt_ad;
        % Limit Indexing To integer Values
        if mod(tstp_stride,1) == 0
            WL = WL(1:tstp_stride:end, :);
            ad_dtime = ad_dtime(1:tstp_stride:end,:);
            dt_final = datenum(dt_wv);
        end
    else % dt are the same , nothing to do
        tstp_stride = dt_ad/dt_wv; % Returns 1
    end
    % Failsafe In Case dt's are not divisible
    if mod(tstp_stride, 1) ~= 0 % timesteps are different but not divisible
        % Try To Get Hourly
        ad_stride = minutes(60)/ad_dtime;
        wv_stride = minutes(60)/wv_dtime;
        dt_final = datenum(0,0,0,0,60,0);
        %
        if mod(ad_stride, 1) == 0 & mod(wv_stride, 1) == 0
            WL = WL(1:ad_stride:end, :);
            ad_dtime = ad_dtime(1:ad_stride:end, :);
            waves = waves(1:wv_stride:end, :);
            wv_dtime = wv_dtime(1:wv_stride:end, :);
        else
            error('Error: Unable to timestep match storm data or build hourly dataset.');
        end
    end
    % If Timestep Is Not Hourly Then Need To Extract Hourly Intervals
    %{
            Notes:
            After Analysis of Storm Suite For NACCS It Was Found That
            Model Output For STWAVE Has One Of Three Timesteps: 15 min,
            30 min or hourly (Tropicals). ExtraTropicals provide hourly
            only. This Correction Assumes Model Run Begins At 00:00
    %}
    % Make Sure That Datasets Are the Sames Size
    if length(waves(:,1))~=length(WL(:,1))
        % Try Matching Timesteps Instead Of Range
        % Find Matching Timestamps STWAVE IN ADCIRC
        [stVec] = ismember(wv_dtime(:,1),ad_dtime(:,1));
        % Find Matching Timestamps ADCIRC IN STWAVE
        adVec = ismember(ad_dtime(:,1),wv_dtime(:,1));
        % Adjust WL Data
        WL = WL(adVec,:);
        % ADjust Wave Data
        waves = waves(stVec,:);
        % Check length Again
        if length(waves(:,1))~=length(WL(:,1))
            % Assign NaN
            storm_data(stm, 2) = {nan(1,1)};
            % Store Bad Storm ID
            ts_storm2rm = [ts_storm2rm;stmID{stm}];
            % Move To Next Storm
            continue;
        end
    end
    % Build Storm Data Matrix [ SSL, Hm0, Tp, wDir, date, dt ]
    storm_mat = [WL,...
        waves,...
        datenum(ad_dtime), repmat(dt_final, length(WL(:,1)), 1)];

    %% REMOVE BAD ENTRIES
    % ADCIRC
    storm_mat(storm_mat(:, 1)<-90, :) = [];
    % STWAVE
    storm_mat(sum(storm_mat(:, 2:3)<-90, 2)>=1, :)=[];
    % Append To Index Variable
    if isempty(storm_mat)
        ts_storm2rm = [ts_storm2rm;stmID{stm}];
        continue;
    end
    % Store Final Results
    storm_data{stm,2} = storm_mat;
end
% Do Unique
ts_storm2rm = unique(ts_storm2rm);
% Print Status
fprintf(1,['\b\b\b\b%3.0f%%' newline],(100*(stm/length(stmID))));
end