function [storm_data, ts_storm2rm] = chs_timeseries_formater(swl_timeseries, hm0_timeseries, storms2rm,...
    STWAVE_headers_location, Tp_special, print_progress)
%{
    %% DESCRIPTION
    This function parses converted CHS data structure to generate a
    number_of_storms x  9 data matrix containing provided CHS regional study
    storm timeseries values. 
    
    %% INPUTS
    swl_timeseries: Converted CHS ADCIRC timeseries storm data in table format. This dataset
                    can be generated by converting CHS data files using StormSim's h5
                    converter (H5_Converter.m). 
    hm0_timeseries: Converted CHS STWAVE timeseries storm data in table format. This dataset
                    can be generated by converting CHS data files using StormSim's h5
                    converter (H5_Converter.m). 
    storms2rm:      Storm ID's of bad storms.
    has_WaterElevation: Boolean indicating if wave model output includes
                        water elevation outputs. Output from 
                        chs_wave_model_header_locator.m

    STWAVE_headers_location: Column index of Hm0, Tp and wave direction in
                             CHS STWAVE outputs. Output from
                             chs_wave_model_header_locator.m
    %% OUTPUTS
    storm_data: MATLAB data structure containing formated chs timeseries
    data.
    
    %% DEV SIGNATURE
    Developed by: Fabian A. Garcia Moreno ERDC-CHL
%}

%% DEFINE INPUTS
%
ts_storm2rm = storms2rm;
% Display Completion Progress Initial Print
if print_progress
    fprintf(1,'   Completion Progress: %3d%%\n',0);
end
% Ensure Data Is Sorted Per Storm ID
swl_timeseries = sortrows(swl_timeseries,'Storm ID','ascend');
hm0_timeseries = sortrows(hm0_timeseries,'Storm ID','ascend');
stmID = cellfun(@str2double,swl_timeseries.('Storm ID'), 'un', false);
% Initialize Storage Matrix
storm_data = [stmID ,cell(length(stmID(:,1)),1)];

%% ADCIRC-STWAVE TIMESERIES MATCHING PROCESS
% Loop Through All Storms
for stm = 1:length(stmID)
    % Print Status
    if print_progress
        fprintf(1,'\b\b\b\b%3.0f%%',(100*(stm/length(stmID))));
    end
    % Skip Bad Storm
    if ismember(stmID{stm},storms2rm) || length(swl_timeseries.("Water Elevation"){stm,1}) == 1
        % Assign NaN
        storm_data(stm, 2) = {nan(1,1)};
        % Store Bad Storm ID
        ts_storm2rm = [ts_storm2rm;stmID{stm}];
        % Move To Next Storm
        continue;
    end

    %% EXTRACT STORM DATA
    % Get Storm Row Index
    pull_indx = cell2mat(stmID) == stmID{stm};
    % ADCIRC
    WL = swl_timeseries.("Water Elevation"){pull_indx,1};
    WL_datestr = num2str(swl_timeseries.("yyyymmddHHMM"){pull_indx,1});

    % STWAVE
    waves = [hm0_timeseries.(STWAVE_headers_location.Hm0){pull_indx,1},...
        hm0_timeseries.(STWAVE_headers_location.Tp){pull_indx,1},...
        hm0_timeseries.(STWAVE_headers_location.wDir){pull_indx,1}];

    % Determine Date Format
    dformat = 'yyyyMMddHHmmss';
    ad_len = length(num2str(swl_timeseries.("yyyymmddHHMM"){pull_indx,1}(1, :)));
    wv_len = length(num2str(hm0_timeseries.("yyyymmddHHMM"){pull_indx,1}(1, :)));


    wv_dtime = datetime(num2str(hm0_timeseries.("yyyymmddHHMM"){pull_indx,1}), "InputFormat", dformat(1:wv_len));
    ad_dtime = datetime(num2str(swl_timeseries.("yyyymmddHHMM"){pull_indx,1}), "InputFormat", dformat(1:ad_len));
    dt_wv = unique(diff(wv_dtime));dt_wv = dt_wv(1);
    dt_ad = unique(diff(ad_dtime));dt_ad = dt_ad(1);

    % Lake Ontrario Special Case
    if Tp_special == 1
        waves(:,3) = waves(:,3).*1.2;
    end

    %% EXTRACT ADCRIC DATA THAT RESIDES INSIDE STWAVE TEMPORAL RANGE
    % Extract ADCIRC Data Points Within Time Window
    WL = WL(ad_dtime>=min(wv_dtime) & ad_dtime<=max(wv_dtime), :);
    ad_dtime = ad_dtime(ad_dtime>=min(wv_dtime) & ad_dtime<=max(wv_dtime), :);

    %% ADJUST MODEL OUTPUTS (IF NEEDED)
    % Adjust Storm Time Matching (If Needed)
    if dt_ad > dt_wv % Wave Model dt Is Finer
        % Define dt and date vector
        dt_final = dt_ad;
        date_final = ad_dtime;
        % Interp Wave Signal To ADCIRC dt
        waves(1) = interp1(wv_dtime, waves(1), ad_dtime, 'linear');
        waves(2) = interp1(wv_dtime, waves(2), ad_dtime, 'linear');
        waves(3) = interp1(wv_dtime, waves(3), ad_dtime, 'linear');
    elseif dt_ad < dt_wv % ADCIRC dt Is Finer
        % Define dt and date vector
        dt_final = dt_wv;
        date_final = wv_dtime;
        % Interp ADCIRC Signal To Wave Model dt
        WL = interp1(ad_dtime, WL, wv_dtime, 'linear');
    else % dt are the same , nothing to do
        %
        dt_final = dt_ad;
        date_final = ad_dtime;
    end
    % Build Storm Data Matrix [ SSL, Hm0, Tp, wDir, date, dt ]
    storm_mat = [WL,...
        waves,...
        datenum(date_final), repmat(datenum(dt_final), length(WL(:,1)), 1)];

    %% REMOVE BAD ENTRIES
    % ADCIRC
    storm_mat(storm_mat(:, 1)<-90, :) = NaN;
    % STWAVE
    storm_mat(sum(storm_mat(:, 2:3)<-90, 2)>=1, 2:3)=NaN;
    % Append To Index Variable
    if isempty(storm_mat)
        ts_storm2rm = [ts_storm2rm;stmID{stm}];
        continue;
    end
    % Store Final Results
    storm_data{stm,2} = storm_mat;
end
% Do Unique
ts_storm2rm = unique(ts_storm2rm);
% Print Status
if print_progress
    fprintf(1,['\b\b\b\b%3.0f%%' newline],(100*(stm/length(stmID))));
end
end