function Storm = chs_peaks_formater(swl_peaks_table,hm0_peaks_table,STWAVE_headers_location)
        %{
    %% DESCRIPTION
    This function parses converted CHS data structure to generate a
    number_of_storms x 4 data matrix containing provided CHS regional study
    storm peak values. 
    
    %% INPUTS
    ADCIRC: Converted CHS peaks storm data in table format. This dataset
    can be generated by converting CHS data files using StormSim's h5
    converter (H5_Converter.m). 
    
    %% OUTPUTS
    config: MATLAB data strcutre containing input file data parsed out as
    individual strucutre fields.
    
    %% DEV SIGNATURE
    Developed by: Fabian A. Garcia Moreno ERDC-CHL
    %}       
    
     %% GRAB INPUT FROM "config"
    %{
        This section meant to provide an easy way to make changes to config
        variable calls without having to alter core code.
    %}
    % Get Storm Data Table
            swl_peaks_table = sortrows(swl_peaks_table,'Storm ID','ascend');
            % Initialize Storm Matrix
            Storm = zeros(height(swl_peaks_table),6);
            % Extract Storm ID From ADCIRC Table
            Storm(:,5) = str2double(swl_peaks_table.("Storm ID"));
            % Extract Water Level From ADyCIRC Table
            Storm(:,1) = swl_peaks_table.("Water Elevation");
            % Assign NaN's If Needed
            Storm(Storm(:,1)==-99999,1) = NaN(1,1);

            %% WAVES (STWAVE, SWAN, WAM)
            % Sort Data Table
            hm0_peaks_table = sortrows(hm0_peaks_table,'Storm ID','ascend');
            %%%%%% Hm0 %%%%%%%
            % Extract Hm0 Peak Values From Data Table
            Storm(:,2) = hm0_peaks_table.(STWAVE_headers_location.Hm0);
            %%%%%% Tp %%%%%%
            % Extract Peak Period From STWAVE Tabley
            Storm(:,3) = hm0_peaks_table.(STWAVE_headers_location.Tp);
            %%%%%% Wave Direction %%%%%%
            % Extract Wave Direction From STWAVE Table
            Storm(:,4) = hm0_peaks_table.(STWAVE_headers_location.wDir);
            % Assign NaN's If Needed
            Storm(sum(Storm(:,2:4)==-99999,2)>=1,2:4) = NaN(1,1);
            Storm(sum(Storm(:,2:4)==0,2)>=1,2:4) = NaN(1,1);
            Storm(:,6) = datenum(swl_peaks_table.("yyyymmddHHMM"),"yyyymmddHHMM");
        end
